-- liquibase formatted sql
-- changeset ddrakhmanov@edu.hse.ru:1 -comment:Comment for user
create table if not exists sessions
(
    id      integer generated by default as identity primary key,
    user_id integer      not null references users,
    token   varchar(255) not null,
    expires timestamp    not null
);
-- rollback delete users;
