version: "3.7"

services:
  database:
    image: postgres
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      timeout: 3s
      interval: 10s
      retries: 12

  app:
    build:
      context: ..
    environment:
      SERVER_PORT: 8081 # Порт на котором будет запускаться приложение.
      # Именно по нему вы сможете запустить ваше приложение
    ports:
      - '8081:8081' # Порты могут быть любые, на ваш вкус
    depends_on:
      - database
