-- liquibase formatted sql
-- changeset ddrakhmanov@edu.hse.ru:1 -comment:Comment for user
create table if not exists orders
(
    id              integer generated by default as identity primary key,
    user_id         integer not null references users,
    from_station_id integer not null references station,
    to_station_id   integer not null references station,
    status          integer not null,
    created         timestamp default CURRENT_TIMESTAMP
);
-- rollback delete users;
