-- liquibase formatted sql
-- changeset ddrakhmanov@edu.hse.ru:1 -comment:Comment for user
create table if not exists users
(
    id       integer generated by default as identity primary key,
    nickname varchar(50)  not null,
    email    varchar(100) not null unique,
    password varchar(255) not null,
    created  timestamp default CURRENT_TIMESTAMP
);
    -- rollback delete users;